### ISSUE TITLE
nginx error appearing when using "local" env type 

### ISSUE THREAD

**Issue by eoinjamesdineen** [rewardenv/reward#31]
I'm trying to build a container in the "local" reward env type and I'm running into this issue 
```
ERROR: The Compose file is invalid because:
Service nginx has neither an image nor a build context specified. At least one must be provided.
```
![image](https://user-images.githubusercontent.com/4701783/197242724-5506a679-8fde-4c0a-adc4-d97b62c36083.png)

The core folder contains a valid Dockerfile (Dockerfile.dev) 

Here is the .env file

```
REWARD_ENV_NAME=e4
REWARD_ENV_TYPE=local
REWARD_WEB_ROOT=/

TRAEFIK_DOMAIN=e4.test
TRAEFIK_SUBDOMAIN=
TRAEFIK_EXTRA_HOSTS=
```

here is the .reward/reward-env.yml file

```
version: "3.5"
services:
  graphql:
    hostname: "{{ .reward_env_name }}-graphql"
    build:
      context: ./core
      dockerfile: Dockerfile.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.custom.tls=true
      - traefik.http.routers.custom.rule=Host(`{{ default "app" .traefik_subdomain }}.{{ default "custom.test" .traefik_domain }}`)
      - traefik.http.services.custom.loadbalancer.server.port=4000
      - traefik.docker.network={{ .reward_env_name }}_default
      - dev.reward.container.name=custom-container
      - dev.reward.environment.name={{ .reward_env_name }}
```

I see on https://github.com/davidalger/m2demo/blob/master/.warden/warden-env.yml that an nginx service is defined. Do I always need to provide one by default?

Thanks!
