### ISSUE TITLE
 ERROR  EACCES: permission denied, open '/var/www/html/magepack.config.js'

### ISSUE THREAD

**Issue by adexandros** [rewardenv/reward#8]
Hi @janosmiko , 

I am getting the error ` ERROR  EACCES: permission denied, open '/var/www/html/magepack.config.js'`  when trying to run the command `reward env exec magepack generate` outside of the shell, as it should be.
I have installed the magepack module, set to 1 the configuration in the .env file, rebuild the environment and everything run smooth up until when the module needs to generate the magepack.config.js file; 
I know it's working ootb for warden and the configuration is almost identical here, am I missing something?

thank you

**Comment by janosmiko** [comment]
Hi @adexandros !

Could you check the permissions of the files and run the following command and post here the results?
```
reward env exec magepack sh
ls -lah
```

**Comment by adexandros** [comment]
```
/var/www/html $ ls -la
total 8
drwxr-xr-x    2 root     root          4096 Jul  1 06:05 .
drwxr-xr-x    3 root     root          4096 Jul  1 06:05 ..
```

**Comment by janosmiko** [comment]
Hm, something's totally wrong there.

Could you run this and paste the results?

```
reward env config
```

**Comment by adexandros** [comment]
```
networks:
  default:
    labels:
      dev.reward.environment.name: abc
      dev.reward.environment.type: magento2
services:
  db:
    command:
    - mysqld
    - --max_allowed_packet=1024M
    - --explicit_defaults_for_timestamp=on
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: magento
      MYSQL_PASSWORD: magento
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_USER: magento
    hostname: abc-mariadb
    image: docker.io/rewardenv/mariadb:10.3
    volumes:
    - dbdata:/var/lib/mysql:rw
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms64m -Xmx512m
      discovery.type: single-node
      xpack.security.enabled: "false"
    hostname: abc-elasticsearch
    image: docker.io/rewardenv/elasticsearch:7.6
    labels:
      traefik.enable: "true"
      traefik.http.routers.abc-elasticsearch.rule: Host(`elasticsearch.abc.test`
)
      traefik.http.routers.abc-elasticsearch.tls: "true"
      traefik.http.services.abc-elasticsearch.loadbalancer.server.port: '9200'
    volumes:
    - esdata:/usr/share/elasticsearch/data:rw
  magepack:
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      TRAEFIK_DOMAIN: abc.test
      TRAEFIK_SUBDOMAIN: app
    extra_hosts:
      app.abc.test: 172.24.0.5
      abc.test: 172.24.0.5
    hostname: abc-magepack
    image: docker.io/rewardenv/magepack:2.3
    volumes:
    - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock:rw
  nginx:
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      NGINX_PUBLIC: /pub
      NGINX_TEMPLATE: magento2[.]conf
      XDEBUG_CONNECT_BACK_HOST: host.docker.internal
    hostname: abc-nginx
    image: docker.io/rewardenv/nginx:1.16
    labels:
      traefik.enable: "false"
      traefik.http.routers.abc-nginx.priority: '2'
      traefik.http.routers.abc-nginx.rule: ' HostRegexp(`{subdomain:.+}.abc.test
`)
        || Host(`abc.test`)'
      traefik.http.routers.abc-nginx.tls: "true"
      traefik.http.services.abc-nginx.loadbalancer.server.port: '80'
    volumes:
    - \\wsl$\Ubuntu-20.04\home\adexandros\projects\ba\abc\.reward\nginx:/etc/ngi
nx/snippets/:rw
    - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock:rw
    - \\wsl$\Ubuntu-20.04\home\adexandros\projects\ba\abc:/var/www/html:cached
  php-debug:
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      CHOWN_DIR_LIST: pub/media
      COMPOSER_MEMORY_LIMIT: '-1'
      NODE_VERSION: '10'
      PHP_IDE_CONFIG: serverName=abc-docker
      SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      TRAEFIK_DOMAIN: abc.test
      TRAEFIK_SUBDOMAIN: app
    extra_hosts:
      app.abc.test: 172.24.0.5
      abc.test: 172.24.0.5
    hostname: abc-php-debug
    image: docker.io/rewardenv/php-fpm:7.4-magento2-debug
    volumes:
    - C:\Users\micro\.reward\ssl\rootca\certs:/etc/ssl/reward-rootca-cert:ro
    - C:\Users\micro\.composer:/home/www-data/.composer:cached
    - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock:rw
    - \\wsl$\Ubuntu-20.04\home\adexandros\projects\ba\abc:/var/www/html:cached
  php-fpm:
    depends_on:
      db:
        condition: service_started
    environment:
      CHOWN_DIR_LIST: pub/media
      COMPOSER_MEMORY_LIMIT: '-1'
      NODE_VERSION: '10'
      SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      TRAEFIK_DOMAIN: abc.test
      TRAEFIK_SUBDOMAIN: app
    extra_hosts:
      app.abc.test: 172.24.0.5
      abc.test: 172.24.0.5
    hostname: abc-php-fpm
    image: docker.io/rewardenv/php-fpm:7.4-magento2
    labels:
      traefik.enable: "true"
      traefik.http.routers.abc-livereload.priority: '2'
      traefik.http.routers.abc-livereload.rule: ' (HostRegexp(`{subdomain:.+}.ps
u.test`)
        || Host(`abc.test`)) && (Path(`/livereload.js`) || Path(`/livereload`))'
      traefik.http.routers.abc-livereload.service: abc-livereload
      traefik.http.routers.abc-livereload.tls: "true"
      traefik.http.services.abc-livereload.loadbalancer.server.port: '35729'
    volumes:
    - C:\Users\micro\.reward\ssl\rootca\certs:/etc/ssl/reward-rootca-cert:ro
    - C:\Users\micro\.composer:/home/www-data/.composer:cached
    - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock:rw
    - \\wsl$\Ubuntu-20.04\home\adexandros\projects\ba\abc:/var/www/html:cached
  rabbitmq:
    hostname: abc-rabbitmq
    image: docker.io/rewardenv/rabbitmq:3.8
    labels:
      traefik.enable: "true"
      traefik.http.routers.abc-rabbitmq.rule: Host(`rabbitmq.abc.test`)
      traefik.http.routers.abc-rabbitmq.tls: "true"
      traefik.http.services.abc-rabbitmq.loadbalancer.server.port: '15672'
    volumes:
    - rabbitmq:/var/lib/rabbitmq:rw
  redis:
    hostname: abc-redis
    image: docker.io/rewardenv/redis:5.0
    volumes:
    - redis:/data:rw
  varnish:
    depends_on:
      nginx:
        condition: service_started
    hostname: abc-varnish
    image: docker.io/rewardenv/varnish:6.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.abc-varnish.priority: '1'
      traefik.http.routers.abc-varnish.rule: ' HostRegexp(`{subdomain:.+}.abc.te
st`)
        || Host(`abc.test`)'
      traefik.http.routers.abc-varnish.tls: "true"
      traefik.http.services.abc-varnish.loadbalancer.server.port: '80'
version: '3.5'
volumes:
  appdata: {}
  dbdata: {}
  esdata: {}
  rabbitmq: {}
  redis: {}
```
